### ISSUE TITLE
How to help this project

### ISSUE THREAD

**Issue by hik4ru** [UltiNaruto/VitaPadClient-java#1]
Hi! I'm a junior java dev (I recently got my academic title in java development, so I don't know how to do this kind of things) and this client is the kind of project I'd like to help if I could in any way. There is any thing I could do to insert Xinput support? Thank you so much for creating this!!

**Comment by UltiNaruto** [comment]
XInput can be done via vJoy : http://vjoystick.sourceforge.net/site/
So basically we would need a java wrapper for vJoy to add this kind of support.
I was also planning to add DInput but it'll need some work too.
That's basically a rewrite from the C++ version of the original application made by Rinnegatamente.
I had no time to push commits as of now since I went back to high school 3rd year and this time I'd like to finish studying once and for all. But if you want to help feel free to push commits. I'll approve them when I got time to test.

**Comment by hik4ru** [comment]
Good luck with that studies! That's the most important thing.

I'm reading about how to implement vJoy in java and it seems like its mandatory to read a .dll library file, and that's pretty complex to do (at least to me). So damn, even if I know java I feel pretty useless to the projects I want to help :/

**Comment by UltiNaruto** [comment]
Thanks. I'll probably have to work on implementing the vJoy wrapper myself since there's actually no public Java wrapper for it. It's normal coding .dll files in java doesn't exist, you don't have to blame yourself for it. I saw your projects and I see that you are actually doing pretty well with your projects, keep doing so. :)
